agents:
  hypothesis_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  process_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  visualization_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  code_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  searcher_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  report_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  quality_review_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  note_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  refiner_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0