agents:
  supervisor_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  sna_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  data_loader_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  report_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  research_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  simulation_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0
  response_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 0.0